fix regex for manifest route
coder/code-server pull request #5219
Opened 2022-05-23 15:03 UTC by marshall-orevillestudios

I noticed that the regex would match other strings than manifest.json such as manifest-json or something-manifest.json

2022-05-23 18:36 UTC, jsjoeio commented
> I noticed that the regex would match other strings than manifest.json such as manifest-json or something-manifest.json

I'm guessing that wasn't intentional but let's double check with @code-asher.

2022-05-23 19:29 UTC, code-asher commented
I think this was because there used to be a `webmanifest.json` link?  But as far as I can tell everything is `manifest.json` now.  Could we get rid of the regex entirely and just do `/manifest.json`?

2022-05-23 22:41 UTC, jsjoeio requested changes
Do you mind addressing @code-asher's feedback? Then we can merge this

2022-08-08 22:43 UTC, jsjoeio commented
@code-asher ready for review

2022-08-09 17:40 UTC, code-asher approved these changes

2022-08-09 17:54 UTC, merged