Update termux.md
coder/code-server pull request #5286
Opened 2022-06-21 16:10 UTC by mrfoxie

Direct installation of `code-server` via `yarn` method in termux android version

2022-06-22 19:55 UTC, jsjoeio requested changes
Thanks for fixing this! Added some suggestions then we can merge

2022-06-22 19:55 UTC, jsjoeio commented on docs/termux.md
> +- [Direct Installation - Yarn Installation](yarn-installation)
```suggestion
- [Direct Installation via yarn](#yarn-installation)
```

2022-06-22 19:55 UTC, jsjoeio commented on docs/termux.md
> +1. Get [Termux](https://f-droid.org/en/packages/com.termux/) from **F-Droid**.
```suggestion
1. Install [Termux](https://f-droid.org/en/packages/com.termux/) from **F-Droid**.
```

2022-06-22 19:55 UTC, jsjoeio commented on docs/termux.md
> +2. We will now change using the following command.
```suggestion
2. Run the following command:
```

2022-06-22 19:55 UTC, jsjoeio commented on docs/termux.md
> +4. Now let's install requirement dependancy.
```suggestion
4. Now let's install required dependencies:
```

2022-06-22 19:55 UTC, jsjoeio commented on docs/termux.md
> +6. Congratulation code-server is installed on your device using the following command.
```suggestion
6. Congratulations! code-serve can now be installed on your device using the following command:
```

2022-06-22 19:55 UTC, jsjoeio commented on docs/termux.md
> +7. If already installed then use the following command for upgradation.
```suggestion
7. To upgrade, run this command:
```

2022-06-23 02:44 UTC, mrfoxie commented
> Thanks for fixing this! Added some suggestions then we can merge

😅😅 sorry for silly mistake

2022-06-23 17:43 UTC, jsjoeio commented
Can you run `yarn fmt` locally?

2022-06-23 17:44 UTC, jsjoeio approved these changes

2022-06-27 04:29 UTC, mrfoxie commented
there is an another way also of installing code-server on Android but it requires another way of installation rather then termux it will take some time but i will be surely adding it into docs sections

2022-08-09 19:15 UTC, merged