Allow opening files at a specific line and column (fixes #5619)
coder/code-server pull request #5620
Opened 2022-10-04 18:28 UTC by danog

Fixes #5619

2022-10-05 17:51 UTC, jsjoeio commented
@danog do you plan to add tests? also, can you add to the PR description steps for testing this locally?

2022-10-05 17:58 UTC, danog commented
Well it's pretty simple to test this locally, just open a workspace and run `code-server -r path/to/file.ext:line:col` from the workspace directory.
It works pretty much the same as before, the only difference is that now line numbers are supported.

2022-10-05 17:59 UTC, danog commented
Debug builds can be tested using `node node_modules/ts-node/dist/bin.js out/node/entry.js -r path/to/file.ext:line:col`

2022-10-05 19:41 UTC, jsjoeio commented
Thank you! I tested locally and it worked like a charm!

https://user-images.githubusercontent.com/3806031/194148046-31f069ca-0e2d-4787-a63d-3382f757a061.mov

Can you please add some tests?

2022-10-05 19:41 UTC, jsjoeio commented on src/node/util.ts
> +
Maybe add a test for this?

2022-10-05 19:42 UTC, jsjoeio commented
cc @code-asher - i tested locally but would love to get your thoughts too 👍🏼

2022-10-05 20:34 UTC, code-asher approved these changes
Looks great.  Glad it was so simple!  Adding a simple test sounds like a good idea to me as well, can pretty much just copy the `isFile` one.

2022-10-06 14:56 UTC, jsjoeio requested changes
Add a test and then we should be good to merge!

2022-10-06 17:39 UTC, jsjoeio approved these changes
Awesome! Looks good to me 👍🏼

2022-10-06 18:12 UTC, merged

2022-10-06 18:12 UTC, jsjoeio commented
Thanks again for your contribution @danog! 🎉

2022-10-11 10:02 UTC, danog commented
Thanks for merging, could I have a tag please? :)

2022-10-11 22:08 UTC, jsjoeio commented
@danog by that do you mean tagged in the release notes? :D

2022-10-12 07:52 UTC, danog commented
I mean a new release, I've been thinking of proposing code-server as an alternative IDE at work, and our workflow heavily relies on the feature introduced in this PR :)

2022-10-13 16:46 UTC, jsjoeio commented
Oh no way, that's exciting! I'm going to see if I can finish https://github.com/coder/code-server/pull/5624 and possibly do https://github.com/coder/code-server/issues/5625 before the next release 🤞🏼 

In the meantime, you _should_ be able to see your changes by doing `npm install -g code-server@beta` (see [here](https://www.npmjs.com/package/code-server/v/4.7.1-beta-ba68656353edfd7a50ef4b5571322e2f0c1b653c)) if you use npm to install code-server.

2022-12-03 15:12 UTC, alanhg commented
> Debug builds can be tested using `node node_modules/ts-node/dist/bin.js out/node/entry.js -r path/to/file.ext:line:col`

I think URL param-like r support is welcome.

2022-12-05 16:51 UTC, jsjoeio commented
We have an open issue for that: https://github.com/coder/code-server/issues/1964