Support HTTP BasicAuth for authentication if $AUTH_USER is set
coder/code-server pull request #7143
Opened 2024-12-29 04:49 UTC by gaberudy

Fixes #7142

2025-01-03 04:02 UTC, code-asher approved these changes
This is neat, thank you!  I know we are not generally adding auth methods, but this seems simple enough to maintain.

2025-01-03 04:02 UTC, code-asher requested changes
Whoops, did not mean to approve quite yet.  :smile:

2025-01-03 15:23 UTC, gaberudy commented on build.sh
> +#!/bin/bash
Yea, I didn't meant to include this.

2025-01-03 15:24 UTC, gaberudy commented on extensions.txt
> +github.copilot
yes, unintended

2025-01-03 15:24 UTC, gaberudy commented on install_locales.sh
> +#!/bin/bash
yes, unintended

2025-01-03 15:24 UTC, gaberudy commented on install_system_extensions.sh
> +#!/bin/bash
yes, unintended

2025-01-03 15:24 UTC, gaberudy commented on package.json
> +    "tslib": "^2.8.1",
I will remove it, but I had a packaging issue without it.

2025-01-03 15:25 UTC, gaberudy commented on src/node/main.ts
> +    logger.info("    - Using password from $PASSWORD")
Ok, I'll incorporate this change

2025-01-03 15:26 UTC, gaberudy commented on src/node/routes/vscode.ts
> +      res.setHeader('WWW-Authenticate', 'Basic realm="Access to the site"')
This is the only place a fresh browser load hits and thus needs this header to prompt the user. I'll update the realm

2025-01-03 15:26 UTC, gaberudy commented on startup.sh
> +#!/bin/bash
Yes

2025-01-03 15:27 UTC, gaberudy commented on src/node/http.ts
> +      return validateBasicAuth(req.headers.authorization, req.args["auth-user"], req.args.password);
I don't think we can check HASHED_PASSWORD in this context.

2025-01-03 15:35 UTC, gaberudy commented on src/node/http.ts
> +    return username === authUser && password === authPassword;
Ok, I'll switch the password comparison to safeCompare

2025-01-06 21:02 UTC, code-asher commented on src/node/http.ts
> +      return validateBasicAuth(req.headers.authorization, req.args["auth-user"], req.args.password);
The hashing is just an internal code-server thing, if you want to give code-server the password but not give it the plain text password.  The hash is not used by the browser or anything like that, if that makes sense.

Whether we are comparing that hashed password with a password submitted from a login form or a password from the basic auth flow, it is all the same to code-server.  Basically, the only difference is `argon2.verify(hashedPassword, passwordFromBasicAuth)` versus `safeCompare(plainTextPassword, passwordFromBasicAuth)`.

2025-01-20 00:00 UTC, gaberudy commented
Superceeded by #7173

2025-01-20 00:00 UTC, closed without merging